### ISSUE TITLE
wenti2

### ISSUE THREAD

**Issue by fantine16** [Kingsland1/top25#2]
https://github.com/Kingsland1/top25/blob/68962c5b352c79a48916b16b32ee0fb0eeeeb11d/top25.py#L48

**Comment by raoraozu** [comment]
loc, iloc， 在使用上，时间+1天的问题， iloc好像必须全部接数字，loc可以接名字，但是又有数字又有名字的。。不知道怎么解决 @fantine16

**Comment by fantine16** [comment]
@raoraozu

**Comment by raoraozu** [comment]
`temp_top25_return_holding[date]=return_open.loc[return_open.index[i + 1], top25.iloc[i - 1, :]`
把date +1,换成 .index[i+1]

**Comment by fantine16** [comment]
赞

**Comment by fantine16** [comment]
https://github.com/Kingsland1/top25/blob/352a3dc8e4de9ac5f5d4fb2b8fcb0be47d51eb66/top25.py#L32
这个含义是啥？

**Comment by fantine16** [comment]
https://github.com/Kingsland1/top25/blob/352a3dc8e4de9ac5f5d4fb2b8fcb0be47d51eb66/top25.py#L48
i+1,i-1,这不是隔了两天？

**Comment by fantine16** [comment]
最后生成的折线图，横坐标时间不是从小到大的？

**Comment by fantine16** [comment]
top25的问题完全搞定～关闭issue
